from random import random
from Alien import AlienType

# This file contains all the level's data, level 1 - 3 are hard coded
# while levels 4 - 10 are randomly generated based on the level (the higher the level the higher
# the aliens level in that level)

LEVELS_LAYOUT = [
    [
        {"x": 0, "y": 5, "type": AlienType.Squid},
        {"x": 9, "y": 5, "type": AlienType.Squid},
        {"x": 18, "y": 5, "type": AlienType.Squid},
        {"x": 27, "y": 5, "type": AlienType.Squid},
        {"x": 36, "y": 5, "type": AlienType.Squid},
        {"x": 45, "y": 5, "type": AlienType.Squid},
        {"x": 54, "y": 5, "type": AlienType.Squid},
        {"x": 63, "y": 5, "type": AlienType.Squid},
        {"x": 72, "y": 5, "type": AlienType.Squid},
        {"x": 80, "y": 5, "type": AlienType.Squid},
        {"x": 0, "y": 9, "type": AlienType.Squid},
        {"x": 9, "y": 9, "type": AlienType.Squid},
        {"x": 18, "y": 9, "type": AlienType.Squid},
        {"x": 27, "y": 9, "type": AlienType.Squid},
        {"x": 36, "y": 9, "type": AlienType.Squid},
        {"x": 45, "y": 9, "type": AlienType.Squid},
        {"x": 54, "y": 9, "type": AlienType.Squid},
        {"x": 63, "y": 9, "type": AlienType.Squid},
        {"x": 72, "y": 9, "type": AlienType.Squid},
        {"x": 80, "y": 9, "type": AlienType.Squid},
        {"x": 0, "y": 13, "type": AlienType.Squid},
        {"x": 9, "y": 13, "type": AlienType.Squid},
        {"x": 18, "y": 13, "type": AlienType.Squid},
        {"x": 27, "y": 13, "type": AlienType.Squid},
        {"x": 36, "y": 13, "type": AlienType.Squid},
        {"x": 45, "y": 13, "type": AlienType.Squid},
        {"x": 54, "y": 13, "type": AlienType.Squid},
        {"x": 63, "y": 13, "type": AlienType.Squid},
        {"x": 72, "y": 13, "type": AlienType.Squid},
        {"x": 80, "y": 13, "type": AlienType.Squid}
    ],
    [
        {"x": 0, "y": 5, "type": AlienType.Octopus},
        {"x": 9, "y": 5, "type": AlienType.Crab},
        {"x": 18, "y": 5, "type": AlienType.Squid},
        {"x": 27, "y": 5, "type": AlienType.Squid},
        {"x": 36, "y": 5, "type": AlienType.Crab},
        {"x": 45, "y": 5, "type": AlienType.Crab},
        {"x": 54, "y": 5, "type": AlienType.Squid},
        {"x": 63, "y": 5, "type": AlienType.Squid},
        {"x": 72, "y": 5, "type": AlienType.Crab},
        {"x": 80, "y": 5, "type": AlienType.Octopus},
        {"x": 0, "y": 9, "type": AlienType.Crab},
        {"x": 9, "y": 9, "type": AlienType.Squid},
        {"x": 18, "y": 9, "type": AlienType.Squid},
        {"x": 27, "y": 9, "type": AlienType.Crab},
        {"x": 36, "y": 9, "type": AlienType.Octopus},
        {"x": 45, "y": 9, "type": AlienType.Octopus},
        {"x": 54, "y": 9, "type": AlienType.Crab},
        {"x": 63, "y": 9, "type": AlienType.Squid},
        {"x": 72, "y": 9, "type": AlienType.Squid},
        {"x": 80, "y": 9, "type": AlienType.Crab},
        {"x": 0, "y": 13, "type": AlienType.Squid},
        {"x": 9, "y": 13, "type": AlienType.Crab},
        {"x": 18, "y": 13, "type": AlienType.Squid},
        {"x": 27, "y": 13, "type": AlienType.Squid},
        {"x": 36, "y": 13, "type": AlienType.Squid},
        {"x": 45, "y": 13, "type": AlienType.Squid},
        {"x": 54, "y": 13, "type": AlienType.Squid},
        {"x": 63, "y": 13, "type": AlienType.Squid},
        {"x": 72, "y": 13, "type": AlienType.Crab},
        {"x": 80, "y": 13, "type": AlienType.Squid}
    ],
    [
        {"x": 0, "y": 5, "type": AlienType.Squid},
        {"x": 9, "y": 5, "type": AlienType.Crab},
        {"x": 18, "y": 5, "type": AlienType.Squid},
        {"x": 27, "y": 5, "type": AlienType.Crab},
        {"x": 36, "y": 5, "type": AlienType.Octopus},
        {"x": 45, "y": 5, "type": AlienType.Octopus},
        {"x": 54, "y": 5, "type": AlienType.Crab},
        {"x": 63, "y": 5, "type": AlienType.Squid},
        {"x": 72, "y": 5, "type": AlienType.Crab},
        {"x": 80, "y": 5, "type": AlienType.Squid},
        {"x": 0, "y": 9, "type": AlienType.Octopus},
        {"x": 9, "y": 9, "type": AlienType.Squid},
        {"x": 18, "y": 9, "type": AlienType.Crab},
        {"x": 27, "y": 9, "type": AlienType.Crab},
        {"x": 36, "y": 9, "type": AlienType.Octopus},
        {"x": 45, "y": 9, "type": AlienType.Octopus},
        {"x": 54, "y": 9, "type": AlienType.Crab},
        {"x": 63, "y": 9, "type": AlienType.Crab},
        {"x": 72, "y": 9, "type": AlienType.Squid},
        {"x": 80, "y": 9, "type": AlienType.Octopus},
        {"x": 0, "y": 13, "type": AlienType.Octopus},
        {"x": 9, "y": 13, "type": AlienType.Crab},
        {"x": 18, "y": 13, "type": AlienType.Crab},
        {"x": 27, "y": 13, "type": AlienType.Squid},
        {"x": 36, "y": 13, "type": AlienType.Squid},
        {"x": 45, "y": 13, "type": AlienType.Squid},
        {"x": 54, "y": 13, "type": AlienType.Squid},
        {"x": 63, "y": 13, "type": AlienType.Crab},
        {"x": 72, "y": 13, "type": AlienType.Crab},
        {"x": 80, "y": 13, "type": AlienType.Octopus}
    ],

]

for i in range(3, 10):
    level = [
        {"x": 0, "y": 5},
        {"x": 9, "y": 5},
        {"x": 18, "y": 5},
        {"x": 27, "y": 5},
        {"x": 36, "y": 5},
        {"x": 45, "y": 5},
        {"x": 54, "y": 5},
        {"x": 63, "y": 5},
        {"x": 72, "y": 5},
        {"x": 80, "y": 5},
        {"x": 0, "y": 9},
        {"x": 9, "y": 9},
        {"x": 18, "y": 9},
        {"x": 27, "y": 9},
        {"x": 36, "y": 9},
        {"x": 45, "y": 9},
        {"x": 54, "y": 9},
        {"x": 63, "y": 9},
        {"x": 72, "y": 9},
        {"x": 80, "y": 9},
        {"x": 0, "y": 13},
        {"x": 9, "y": 13},
        {"x": 18, "y": 13},
        {"x": 27, "y": 13},
        {"x": 36, "y": 13},
        {"x": 45, "y": 13},
        {"x": 54, "y": 13},
        {"x": 63, "y": 13},
        {"x": 72, "y": 13},
        {"x": 80, "y": 13}
    ]
    for alien in level:
        alien['type'] = AlienType.Octopus if random() < (
            i - 2) * 0.125 else AlienType.Crab if random() < (i - 2) * 0.1 else AlienType.Squid
    LEVELS_LAYOUT.append(level)
